export class Config {
  static TRWASTAKINGAMOUNT = 2500; //AMOUNT TRWA TO STAKE ON A POOL (FAUCET GIVE 15K TRWA CURRENTLY THERE 5 POOL) EX: 1000
  static GWEIPRICE = 1.5; //GWEI PRICE
  static WAITFORBLOCKCONFIRMATION = true; //IF TRUE AFTER TX EXECUTED BOT WILL WAIT TX TO BE MINED FIRST, IF FALSE AFTER TX EXECUTED BOT WILL CONTINUE TO NEXT TX
  static DISPLAY = "TWIST"; //TWIST or BLESS
}
